name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16', '18', '20']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn eslint '*/**/*.{js,ts}' --quiet

      - name: Lint commit messages
        run: yarn commitlint --from=HEAD~1 --to=HEAD

      - name: Run unit tests
        run: yarn test

      - name: Run integration tests
        run: yarn test:integration

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Build documentation
        run: yarn build:doc

      - name: Run semantic-release
        run: yarn semantic-release

      - name: Deploy documentation
        run: yarn deploy:doc
